import type { NextPage } from 'next'
import Head from 'next/head'
import { useMemo, useState } from 'react'
import styled from 'styled-components'

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  min-height: 100vh;
  padding: 0 0.5rem;
`

const Main = styled.main`
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 5rem 0;
`

const Grid = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  max-width: 500px;
  margin-top: 3rem;

  @media (max-width: 600px) {
    flex-direction: column;
    width: 100%;
  }
`

const Area = styled.div<{ click: boolean }>`
  width: 50px;
  height: 50px;
  border: 1px solid black;
  background-color: ${(props) => (props.click ? 'transparent' : 'green')};
  text-align: center;
  line-height: 50px;
`

const Footer = styled.footer`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;

  a {
    display: flex;
    flex-grow: 1;
    align-items: center;
    justify-content: center;
  }
`

const Logo = styled.span`
  height: 1em;
  margin-left: 0.5rem;
`

const Home: NextPage = () => {
  const [level, setLevel] = useState(0)

  const fieldComponet = useMemo(() => {
    return {
      len: level < 1 ? 8 : 16,
      margin: level < 1 ? 2 : 4,
    }
  }, [level])

  const fieldData = () => {
    const fc = fieldComponet
    return [...Array(fc.len + 2)].map(() => [...Array(fc.len + fc.margin + 2)].map(() => 0))
  }

  const fieldClick = () => {
    const fc = fieldComponet
    return [...Array(fc.len + 2)].map(() => [...Array(fc.len + fc.margin + 2)].map(() => false))
  }

  const [field, setField] = useState(fieldClick)

  const shuffle = (len: number) => {
    const arr = [...Array(len)].map((elm, idx) => idx + 1)
    let a = arr.length
    while (a) {
      const j = Math.floor(Math.random() * a)
      const t = arr[--a]
      arr[a] = arr[j]
      arr[j] = t
    }
    return arr
  }

  const clickPanel = (val: number, x: number, y: number) => {
    const displayVal = val < 99 && field[x][y] ? val : ''
    return val === 99 && field[x][y] ? <i className="fas fa-bomb fa-lg" /> : displayVal
  }

  // prettier-ignore
  const directions: number[][] = [
    [-1, 0], [-1, 1], [0, 1], [1, 1], [1, 0], [1, -1], [0, -1], [-1, -1]
  ]

  const bombSet = () => {
    const fc = fieldComponet
    const a1 = shuffle(fc.len)
    const a2 = shuffle(fc.len)
    const bombSetFld = fieldData()
    for (let i = 0; i < fc.len; i++) {
      const x = a1[i]
      const y = a2[i]
      bombSetFld[x][y] = 99
      for (const direction of directions) {
        const newX = x + direction[0] * 1
        const newY = y + direction[1] * 1
        // if (newX < 0 || newY < 0 || newX > fc.len - 1 || newY > fc.len - 1) continue
        if (bombSetFld[newX][newY] != 99) bombSetFld[newX][newY] += 1
      }
    }
    return bombSetFld
  }
  const [bombPosition, setBombPosition] = useState(bombSet)

  const zeroOpen = (field: boolean[][], x: number, y: number) => {
    const fc = fieldComponet
    const candidates = []
    for (const direction of directions) {
      for (let n = 1; n < fc.len; n++) {
        const newX = x + direction[0] * n
        const newY = y + direction[1] * n
        // if (newX < 0 || newY < 0 || newX > fc.len - 1 || newY > fc.len + fc.margin - 1) break
        if (bombPosition[newX][newY] === 0) {
          candidates.push({ row: newX, col: newY })
        } else {
          break
        }
      }
      if (candidates.length > 0) {
        // 隣あう0のマスをオープンする
        for (const cell of candidates) field[cell.row][cell.col] = true
      }
      candidates.splice(0, candidates.length)
    }
    return field
  }

  const overClick = (x: number, y: number) => {
    let newField = JSON.parse(JSON.stringify(field))
    if (bombPosition[x][y] === 0) newField = zeroOpen(newField, x, y)
    newField[x][y] = true
    setField(newField)
  }

  const clear = () => {
    setField(fieldClick())
    setBombPosition(bombSet)
  }
  return (
    <Container>
      <Head>
        <title>Minesweeper study</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet" />
      </Head>

      <Main>
        <button onClick={clear}>クリア</button>
        <Grid>
          {bombPosition.map((row, x) =>
            row.map((col, y) => (
              <Area key={`${x}-${y}`} click={field[x][y]} onClick={() => overClick(x, y)}>
                {clickPanel(col, x, y)}
              </Area>
            ))
          )}
        </Grid>
      </Main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Logo>
            <img src="vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Logo>
        </a>
      </Footer>
    </Container>
  )
}

export default Home
